### ISSUE TITLE
include elementor templates?

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/elementor-addon-widgets#11]
@selul @abaicus an idea to market/distribute the Elementor templates library would be to include the Elementor tagged templates and template directory functionality in this plugin, which will be like : Elementor add-ons & templates.

Ideally the orbitfox module will develop towards a more complete/generic solution that won't be suitable for people looking specifically for elementor stuff.

By merging those things and releasing both the templates+ few extra widgets we can experiment much sooner with a premium version on themeisle.com, while orbitfox will get on his own domain.

**Comment by andreilupu** [comment]
This feature was added in #14 and I think we can put this issue down.
