### ISSUE TITLE
ti landing page

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/elementor-addon-widgets#12]
@abaicus @selul since we do have plans for a pro version for this specific plugin, we should have a plugin page on our site for both free/pro version.

**Comment by abaicus** [comment]
@dascalescuro Can we have 2-3 texts to showcase what the plugin does right now?

We have the same widgets as in OrbitFox, the Content Forms module, the template directory, it adds a page template that should work with the more popular themes around, and thus the templates from templatedir would work just fine.

**Comment by ineagu** [comment]
@abaicus there are few stuff that are part of this release as well: 

- [ ] Find a new brandable name that can incorporate the whole templates+widgets, something like TiElements - Elementor Templates & Addons
- [ ] Please do not spend as much time on creatives as on obfx :D 
- [ ] redo w.org description+screenshots
- [ ] see with @andreilupu how the dashboard page will come along and incorporate the new name in dashboard

**Comment by abaicus** [comment]
@ineagu ATM We don't have a dashboard page for this plugin. We only have the template directory, which should be renamed from `Orbit Fox Template Directory`.

**Comment by dascalescuro** [comment]
@abaicus this is my take on the copy of the LP -> [click here](https://docs.google.com/document/d/157i_a2-YFXiZqU9eYbU4rmiu9P5GJGfx85IZk9c3jZg/edit?usp=sharing) 

Let me know if I missed something.

If you want help with the WP description, let me know if there is something specific you have in mind.

**Comment by abaicus** [comment]
@dascalescuro I'll have a look and let you know 👍 thanks for this!
