### ISSUE TITLE
merge the template directory module

### ISSUE THREAD

**Issue by selul** [Codeinwp/elementor-addon-widgets#13]
@andreilupuI would need your help in adding the whole templates-directory module from obfx, in this plugin. 

I'm not sure if we have an admin menu item for this plugin, if we do, we will add under it, if not, it will be under appearances sections.

We can use the same strategy with composer for sharing the code between obfx and this plugin.

Between the coding sessions, if you could have a look at the code of this plugin and check if we can improve the things that work now in some way, would be ideal. I'm thinking of some kind of code audit. 

Let me know if you have any questions or if you want to have a call to clear things.

**Comment by ineagu** [comment]
I would recommend to create a menu item for the plugin, we might need some settings panels to disable modules, recommend pro version, or configure full-width template for e.g, under appearence might be confusing.

**Comment by andreilupu** [comment]
This is already merged
