### ISSUE TITLE
Notice: Undefined index: before_widget

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/elementor-addon-widgets#29]
When WP_DEBUG mode ON, following error arises:

Notice: Undefined index: before_widget in /home/diatzacl/public_html/wp-content/plugins/elementor-addon-widgets/vendor/codeinwp/elementor-extra-widgets/widgets/woo/featured-products.php on line 78

When adding “Woo Featured Products” widget from WooCommerce plugin.

Ticket: https://wordpress.org/support/topic/error-debug-mode-on-2/#post-10235228

@selul @rodica-andronache

**Comment by radu-themeisle** [comment]
+1 for **_recent-products.php on line 76_**

Ticket: https://secure.helpscout.net/conversation/860453184/189559?folderId=212385

cc: @contactashish13

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/elementor-extra-widgets/pull/14

**Comment by Vishakha-Patel** [comment]
@radu-themeisle Can you give this PR a try?

Not working for me. Maybe, there is something missing on my end.

**Comment by radu-themeisle** [comment]
@Vishakha-Patel I managed to give this issue a go, unfortunately I cannot replicate the issue, I don't get any PHP error.

**Comment by contactashish13** [comment]
@abaicus do you want to take a stab at testing this? :grin:
