### ISSUE TITLE
PRO version experiment

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/elementor-addon-widgets#9]
In order to launch:

- [ ] - Landing Pages
- [ ] - Demo Site
- [ ] - Product Name: enhancepress.com vs sizzify.com
- [ ] - Develop 4 new widgets
- [ ] - Integrate extra templates from analogwp
- [ ] - develop template sync feature ( this should be pretty basic, a sync button, which will check if license is valid and bring new pro templates if they exist )
- [ ] - list pro templates in template directory for upsell reason.

Here is how we can easily upsell : https://www.dropbox.com/s/qx47pxnk02dfnjq/Screenshot%202018-02-19%2019.29.00.png?dl=0 .

pricing : $39 / $89 / $149

cc @selul @abaicus 

We should really go in MVP mode and get an idea about interest before working more on it, however there are still few things to do, how long do you estimate the project will take? Can you guys further expand specs and get help on some tasks?

**Comment by ineagu** [comment]
@andreilupu this is something that we can work on after the domainwheler mvp, @abaicus can help with frontend bites and ideas, here are few ideas for pro widgets:

1. Animated Headline
2. FlipBox
3. Popup Modal
4. Chart 
5. Table
6. Review Box ( add a box looking similar to wppr )
7. https://shop.webtechstreet.com/downloads/anywhere-elementor-pro/

From an overall perspective I am interested in picking something that will allow us to stay in the 2-weeks timeframe for pro ( pro templates + landing+demo +addons)

**Comment by ineagu** [comment]
**Animated Headline**
- we should use [typed.js](https://mattboldt.com/typed.js/) and a setting panel like this to allow users to use this module: https://www.dropbox.com/s/87zgrjxsbo7l3bs/Screenshot%202018-02-19%2018.25.49.png?dl=0, style tab should be pretty much standard, without too many options.


**FlipCard**

- This should be a pretty simple element that will turn on hover, main settings would like : https://www.dropbox.com/s/xxr4k2y8c3u2liz/Screenshot%202018-02-19%2018.38.22.png?dl=0, just we'll use a wsying field there. 
- Back section will also have the ability to add multiple buttons, will a default one added.
- Use Default content from materialkit pro.

**Review Box**

Add a box like WPPR : https://www.dropbox.com/s/nbldrttn3yykqt3/Screenshot%202018-02-19%2019.11.48.png?dl=0, it will have elements like : Review Title, image, rating, price,button /  PROs & Cons which will be a separate sub-tab with 2 repeater fields.

**Share Buttons**

Create a block with following settings: https://www.dropbox.com/s/l7v6zj6f681jpm6/Screenshot%202018-02-19%2019.23.20.png?dl=0, keep settings as a minimum, same for style settings: https://www.dropbox.com/s/bzymd1vwqkt4qq7/Screenshot%202018-02-19%2019.25.00.png?dl=0 .


-----
As I have mentioned before is important that those can look good enough when added to most of the themes, we'll probably further customize them and offer skins if the project works.

Settings should be kept at minimum and blocks can do just 1 thing well, not everything for everybody.

**Comment by selul** [comment]
@andreilupu let's tackle this after we finish site import.

The codebase will be into this plugin but needs to have the logic separated as we might reuse it into orbit fox using the elementor-extra-widgets library.
In the lite version we will add the icons for this modules, but in the disabled state, when users will add them into the page, they will see an upsell message, only when they are using the elementor editor, in the frontend will not echo anything.
